name: Dev Docker Multi-arch Image CI & CD

on:
  push:
    branches:
      - ci

jobs:
  build:
    name: Running Compile Next Multi-arch Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PicImpact
        uses: actions/checkout@v4
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm i && pnpm add prisma @prisma/client
      - name: Build Next
        run: pnpm run prisma:generate && pnpm run build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: set_up_buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push dev
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/picimpact:dev